language: php
php:
  - "7.2"
addons:
  mariadb: 10.4
cache:
  directories:
    - node_modules
    - vendor
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project 754645051433 --token $FIREBASE_TOKEN